### ISSUE TITLE
Json is no working, seems to be missing delimiter, wasn't closed properly

### ISSUE THREAD

**Issue by N3evin** [MrKev312/AmiiboGameListGenerator#2]
After generating, 

```
Done generating the JSON!
However, the following games could not be added to the database:
        Shovel Knight Showdown (Wii U)
```

the output of the JSON format is incorrect. Eg. seems to be missing closing brackets.

Edit: Seems to be missing certain data too after manually fixing the missing closing brackets, like `0x38c0000003911602`, not too sure what else is missing, but could be due to incorrect format, that certain data might be missing.

**Comment by MrKev312** [comment]
I think this is caused by the streamwriter breaking somehow, I've replaced that part with a slower but hopefully working version. Could you try this version and report if it works?
[Release.1.2.2.zip](https://github.com/MrKev312/AmiiboGameListGenerator/files/6797158/Release.1.2.2.zip)

**Comment by N3evin** [comment]
This seems to be working, I will have to update amiiboapi with it. Will you be making a release of this version?

**Comment by MrKev312** [comment]
Yeah!
